# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ohtl.ui'
#
# Created: Tue Dec 26 21:58:01 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(760, 540)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/image2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(430, 490, 101, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(550, 490, 101, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.ohtl_display = QtGui.QTextEdit(Dialog)
        self.ohtl_display.setGeometry(QtCore.QRect(10, 10, 741, 301))
        self.ohtl_display.setMouseTracking(False)
        self.ohtl_display.setAcceptDrops(True)
        self.ohtl_display.setReadOnly(True)
        self.ohtl_display.setObjectName(_fromUtf8("ohtl_display"))
        self.ohtl_end = QtGui.QPushButton(Dialog)
        self.ohtl_end.setGeometry(QtCore.QRect(110, 500, 81, 31))
        self.ohtl_end.setObjectName(_fromUtf8("ohtl_end"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(420, 390, 171, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.ohtl_open = QtGui.QPushButton(Dialog)
        self.ohtl_open.setGeometry(QtCore.QRect(10, 440, 71, 31))
        self.ohtl_open.setObjectName(_fromUtf8("ohtl_open"))
        self.ohtl_start = QtGui.QPushButton(Dialog)
        self.ohtl_start.setGeometry(QtCore.QRect(10, 500, 81, 31))
        self.ohtl_start.setObjectName(_fromUtf8("ohtl_start"))
        self.ohtl_confirm = QtGui.QPushButton(Dialog)
        self.ohtl_confirm.setGeometry(QtCore.QRect(560, 350, 75, 21))
        self.ohtl_confirm.setObjectName(_fromUtf8("ohtl_confirm"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(220, 320, 71, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.ohtl_zbconfirm = QtGui.QPushButton(Dialog)
        self.ohtl_zbconfirm.setGeometry(QtCore.QRect(220, 480, 75, 21))
        self.ohtl_zbconfirm.setObjectName(_fromUtf8("ohtl_zbconfirm"))
        self.ohtl_serial = QtGui.QComboBox(Dialog)
        self.ohtl_serial.setGeometry(QtCore.QRect(10, 380, 69, 21))
        self.ohtl_serial.setObjectName(_fromUtf8("ohtl_serial"))
        self.ohtl_zbinfo = QtGui.QPushButton(Dialog)
        self.ohtl_zbinfo.setGeometry(QtCore.QRect(220, 510, 75, 21))
        self.ohtl_zbinfo.setObjectName(_fromUtf8("ohtl_zbinfo"))
        self.ohtl_zbcmid = QtGui.QLineEdit(Dialog)
        self.ohtl_zbcmid.setGeometry(QtCore.QRect(220, 380, 71, 20))
        self.ohtl_zbcmid.setInputMask(_fromUtf8(""))
        self.ohtl_zbcmid.setObjectName(_fromUtf8("ohtl_zbcmid"))
        self.ohtl_dirmin = QtGui.QLineEdit(Dialog)
        self.ohtl_dirmin.setGeometry(QtCore.QRect(430, 410, 91, 20))
        self.ohtl_dirmin.setObjectName(_fromUtf8("ohtl_dirmin"))
        self.ohtl_comboBox = QtGui.QComboBox(Dialog)
        self.ohtl_comboBox.setGeometry(QtCore.QRect(110, 380, 69, 22))
        self.ohtl_comboBox.setObjectName(_fromUtf8("ohtl_comboBox"))
        self.ohtl_comboBox.addItem(_fromUtf8(""))
        self.ohtl_comboBox.setItemText(0, _fromUtf8(""))
        self.ohtl_comboBox.addItem(_fromUtf8(""))
        self.ohtl_comboBox.addItem(_fromUtf8(""))
        self.ohtl_comboBox.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(220, 340, 121, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.ohtl_clean = QtGui.QPushButton(Dialog)
        self.ohtl_clean.setGeometry(QtCore.QRect(10, 320, 75, 21))
        self.ohtl_clean.setObjectName(_fromUtf8("ohtl_clean"))
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(190, 320, 20, 271))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.ohtl_lon = QtGui.QLineEdit(Dialog)
        self.ohtl_lon.setGeometry(QtCore.QRect(550, 510, 101, 20))
        self.ohtl_lon.setObjectName(_fromUtf8("ohtl_lon"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(420, 330, 131, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.ohtl_unslinked = QtGui.QPushButton(Dialog)
        self.ohtl_unslinked.setGeometry(QtCore.QRect(320, 380, 81, 21))
        self.ohtl_unslinked.setObjectName(_fromUtf8("ohtl_unslinked"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 360, 54, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ohtl_id = QtGui.QLineEdit(Dialog)
        self.ohtl_id.setGeometry(QtCore.QRect(430, 350, 91, 20))
        self.ohtl_id.setObjectName(_fromUtf8("ohtl_id"))
        self.ohtl_slinked = QtGui.QPushButton(Dialog)
        self.ohtl_slinked.setGeometry(QtCore.QRect(320, 350, 81, 21))
        self.ohtl_slinked.setObjectName(_fromUtf8("ohtl_slinked"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(320, 320, 141, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(420, 440, 181, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.ohtl_info = QtGui.QPushButton(Dialog)
        self.ohtl_info.setGeometry(QtCore.QRect(320, 510, 81, 21))
        self.ohtl_info.setObjectName(_fromUtf8("ohtl_info"))
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(300, 320, 20, 271))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.ohtl_lat = QtGui.QLineEdit(Dialog)
        self.ohtl_lat.setGeometry(QtCore.QRect(430, 510, 91, 20))
        self.ohtl_lat.setObjectName(_fromUtf8("ohtl_lat"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(220, 410, 91, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.ohtl_schipdir = QtGui.QPushButton(Dialog)
        self.ohtl_schipdir.setGeometry(QtCore.QRect(560, 410, 81, 21))
        self.ohtl_schipdir.setObjectName(_fromUtf8("ohtl_schipdir"))
        self.ohtl_stime = QtGui.QPushButton(Dialog)
        self.ohtl_stime.setGeometry(QtCore.QRect(320, 430, 81, 21))
        self.ohtl_stime.setObjectName(_fromUtf8("ohtl_stime"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 360, 54, 12))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ohtl_zbctid = QtGui.QLineEdit(Dialog)
        self.ohtl_zbctid.setGeometry(QtCore.QRect(220, 450, 71, 20))
        self.ohtl_zbctid.setObjectName(_fromUtf8("ohtl_zbctid"))
        self.ohtl_dirmax = QtGui.QLineEdit(Dialog)
        self.ohtl_dirmax.setGeometry(QtCore.QRect(430, 460, 91, 20))
        self.ohtl_dirmax.setObjectName(_fromUtf8("ohtl_dirmax"))
        self.ohtl_close = QtGui.QPushButton(Dialog)
        self.ohtl_close.setGeometry(QtCore.QRect(110, 440, 71, 31))
        self.ohtl_close.setObjectName(_fromUtf8("ohtl_close"))
        self.ohtl_unstime = QtGui.QPushButton(Dialog)
        self.ohtl_unstime.setGeometry(QtCore.QRect(320, 460, 81, 21))
        self.ohtl_unstime.setObjectName(_fromUtf8("ohtl_unstime"))
        self.ohtl_unschipdir = QtGui.QPushButton(Dialog)
        self.ohtl_unschipdir.setGeometry(QtCore.QRect(560, 460, 81, 21))
        self.ohtl_unschipdir.setObjectName(_fromUtf8("ohtl_unschipdir"))
        self.ohtl_checkvhf = QtGui.QPushButton(Dialog)
        self.ohtl_checkvhf.setGeometry(QtCore.QRect(670, 340, 75, 21))
        self.ohtl_checkvhf.setObjectName(_fromUtf8("ohtl_checkvhf"))
        self.ohtl_openvhf = QtGui.QPushButton(Dialog)
        self.ohtl_openvhf.setGeometry(QtCore.QRect(670, 370, 75, 21))
        self.ohtl_openvhf.setObjectName(_fromUtf8("ohtl_openvhf"))
        self.ohtl_closevhf = QtGui.QPushButton(Dialog)
        self.ohtl_closevhf.setGeometry(QtCore.QRect(670, 400, 75, 21))
        self.ohtl_closevhf.setObjectName(_fromUtf8("ohtl_closevhf"))
        self.ohtl_chechzb = QtGui.QPushButton(Dialog)
        self.ohtl_chechzb.setGeometry(QtCore.QRect(670, 450, 75, 21))
        self.ohtl_chechzb.setObjectName(_fromUtf8("ohtl_chechzb"))
        self.ohtl_openzb = QtGui.QPushButton(Dialog)
        self.ohtl_openzb.setGeometry(QtCore.QRect(670, 480, 75, 21))
        self.ohtl_openzb.setObjectName(_fromUtf8("ohtl_openzb"))
        self.ohtl_closezb = QtGui.QPushButton(Dialog)
        self.ohtl_closezb.setGeometry(QtCore.QRect(670, 510, 75, 21))
        self.ohtl_closezb.setObjectName(_fromUtf8("ohtl_closezb"))
        self.line_6 = QtGui.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(650, 320, 20, 271))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(220, 360, 91, 20))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(220, 430, 91, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "超高主机配置", None))
        self.label_17.setText(_translate("Dialog", "主机纬度（Hex）", None))
        self.label_18.setText(_translate("Dialog", "主机经度（Hex）", None))
        self.ohtl_end.setText(_translate("Dialog", "关闭配置模式", None))
        self.label_20.setText(_translate("Dialog", "船舶航向最小值（Hex）", None))
        self.ohtl_open.setText(_translate("Dialog", "打开串口", None))
        self.ohtl_start.setText(_translate("Dialog", "开启配置模式", None))
        self.ohtl_confirm.setText(_translate("Dialog", "确认配置", None))
        self.label_14.setText(_translate("Dialog", "ZigBee配置:", None))
        self.ohtl_zbconfirm.setText(_translate("Dialog", "确认配置", None))
        self.ohtl_zbinfo.setText(_translate("Dialog", "ZigBee信息", None))
        self.ohtl_zbcmid.setText(_translate("Dialog", "8001", None))
        self.ohtl_dirmin.setText(_translate("Dialog", "0000", None))
        self.ohtl_comboBox.setItemText(1, _translate("Dialog", "9600", None))
        self.ohtl_comboBox.setItemText(2, _translate("Dialog", "38400", None))
        self.ohtl_comboBox.setItemText(3, _translate("Dialog", "115200", None))
        self.label_15.setText(_translate("Dialog", "ZigBee本机地址", None))
        self.ohtl_clean.setText(_translate("Dialog", "清屏", None))
        self.ohtl_lon.setText(_translate("Dialog", "00114f97", None))
        self.label_19.setText(_translate("Dialog", "主机ID（Hex,max=ffff）", None))
        self.ohtl_unslinked.setText(_translate("Dialog", "隐藏发送信息", None))
        self.label_4.setText(_translate("Dialog", "串口", None))
        self.ohtl_id.setText(_translate("Dialog", "0001", None))
        self.ohtl_slinked.setText(_translate("Dialog", "显示发送信息", None))
        self.label.setText(_translate("Dialog", "超高主机配置:", None))
        self.label_21.setText(_translate("Dialog", "船舶航向最大值（Hex,max=ffff）", None))
        self.ohtl_info.setText(_translate("Dialog", "主机信息", None))
        self.ohtl_lat.setText(_translate("Dialog", "0003887d", None))
        self.label_16.setText(_translate("Dialog", "ZigBee对方地址", None))
        self.ohtl_schipdir.setText(_translate("Dialog", "显示船舶航向", None))
        self.ohtl_stime.setText(_translate("Dialog", "显示时间", None))
        self.label_5.setText(_translate("Dialog", "波特率", None))
        self.ohtl_zbctid.setText(_translate("Dialog", "8002", None))
        self.ohtl_dirmax.setText(_translate("Dialog", "0e10", None))
        self.ohtl_close.setText(_translate("Dialog", "关闭串口", None))
        self.ohtl_unstime.setText(_translate("Dialog", "隐藏时间", None))
        self.ohtl_unschipdir.setText(_translate("Dialog", "隐藏船舶航向", None))
        self.ohtl_checkvhf.setText(_translate("Dialog", "查询VHF", None))
        self.ohtl_openvhf.setText(_translate("Dialog", "开启VHF", None))
        self.ohtl_closevhf.setText(_translate("Dialog", "关闭VHF", None))
        self.ohtl_chechzb.setText(_translate("Dialog", "查询ZigBee", None))
        self.ohtl_openzb.setText(_translate("Dialog", "开启ZigBee", None))
        self.ohtl_closezb.setText(_translate("Dialog", "关闭ZigBee", None))
        self.label_22.setText(_translate("Dialog", "Hex,max=ffff", None))
        self.label_23.setText(_translate("Dialog", "Hex,max=ffff", None))

import winico_rc
