# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brtl.ui'
#
# Created: Tue Dec 26 21:58:33 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(762, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/image2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.brtl_dirmax = QtGui.QLineEdit(Dialog)
        self.brtl_dirmax.setGeometry(QtCore.QRect(420, 460, 91, 20))
        self.brtl_dirmax.setObjectName(_fromUtf8("brtl_dirmax"))
        self.brtl_schipdir = QtGui.QPushButton(Dialog)
        self.brtl_schipdir.setGeometry(QtCore.QRect(320, 490, 81, 21))
        self.brtl_schipdir.setObjectName(_fromUtf8("brtl_schipdir"))
        self.brtl_open = QtGui.QPushButton(Dialog)
        self.brtl_open.setGeometry(QtCore.QRect(10, 410, 71, 21))
        self.brtl_open.setObjectName(_fromUtf8("brtl_open"))
        self.brtl_slinked = QtGui.QPushButton(Dialog)
        self.brtl_slinked.setGeometry(QtCore.QRect(320, 350, 81, 21))
        self.brtl_slinked.setObjectName(_fromUtf8("brtl_slinked"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(410, 330, 131, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(300, 320, 20, 271))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.brtl_zbcmid = QtGui.QLineEdit(Dialog)
        self.brtl_zbcmid.setGeometry(QtCore.QRect(220, 390, 71, 20))
        self.brtl_zbcmid.setInputMask(_fromUtf8(""))
        self.brtl_zbcmid.setObjectName(_fromUtf8("brtl_zbcmid"))
        self.brtl_unstime = QtGui.QPushButton(Dialog)
        self.brtl_unstime.setGeometry(QtCore.QRect(320, 450, 81, 21))
        self.brtl_unstime.setObjectName(_fromUtf8("brtl_unstime"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(220, 350, 121, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(320, 320, 141, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.brtl_unslinked = QtGui.QPushButton(Dialog)
        self.brtl_unslinked.setGeometry(QtCore.QRect(320, 380, 81, 21))
        self.brtl_unslinked.setObjectName(_fromUtf8("brtl_unslinked"))
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(190, 320, 20, 271))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.brtl_end = QtGui.QPushButton(Dialog)
        self.brtl_end.setGeometry(QtCore.QRect(110, 450, 81, 21))
        self.brtl_end.setObjectName(_fromUtf8("brtl_end"))
        self.brtl_display = QtGui.QTextEdit(Dialog)
        self.brtl_display.setGeometry(QtCore.QRect(10, 10, 741, 301))
        self.brtl_display.setMouseTracking(False)
        self.brtl_display.setAcceptDrops(True)
        self.brtl_display.setReadOnly(True)
        self.brtl_display.setObjectName(_fromUtf8("brtl_display"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(420, 490, 101, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 350, 54, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.brtl_start = QtGui.QPushButton(Dialog)
        self.brtl_start.setGeometry(QtCore.QRect(10, 450, 81, 21))
        self.brtl_start.setObjectName(_fromUtf8("brtl_start"))
        self.brtl_zbconfirm = QtGui.QPushButton(Dialog)
        self.brtl_zbconfirm.setGeometry(QtCore.QRect(220, 510, 75, 21))
        self.brtl_zbconfirm.setObjectName(_fromUtf8("brtl_zbconfirm"))
        self.brtl_id = QtGui.QLineEdit(Dialog)
        self.brtl_id.setGeometry(QtCore.QRect(420, 350, 91, 20))
        self.brtl_id.setObjectName(_fromUtf8("brtl_id"))
        self.brtl_checkvhf = QtGui.QPushButton(Dialog)
        self.brtl_checkvhf.setGeometry(QtCore.QRect(10, 500, 75, 21))
        self.brtl_checkvhf.setObjectName(_fromUtf8("brtl_checkvhf"))
        self.brtl_stime = QtGui.QPushButton(Dialog)
        self.brtl_stime.setGeometry(QtCore.QRect(320, 420, 81, 21))
        self.brtl_stime.setObjectName(_fromUtf8("brtl_stime"))
        self.brtl_dirmin = QtGui.QLineEdit(Dialog)
        self.brtl_dirmin.setGeometry(QtCore.QRect(420, 410, 91, 20))
        self.brtl_dirmin.setObjectName(_fromUtf8("brtl_dirmin"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 350, 54, 12))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.brtl_unschipdir = QtGui.QPushButton(Dialog)
        self.brtl_unschipdir.setGeometry(QtCore.QRect(320, 520, 81, 21))
        self.brtl_unschipdir.setObjectName(_fromUtf8("brtl_unschipdir"))
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(410, 440, 181, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.brtl_chechzb = QtGui.QPushButton(Dialog)
        self.brtl_chechzb.setGeometry(QtCore.QRect(110, 500, 75, 21))
        self.brtl_chechzb.setObjectName(_fromUtf8("brtl_chechzb"))
        self.brtl_confirm = QtGui.QPushButton(Dialog)
        self.brtl_confirm.setGeometry(QtCore.QRect(680, 320, 75, 21))
        self.brtl_confirm.setObjectName(_fromUtf8("brtl_confirm"))
        self.brtl_closezb = QtGui.QPushButton(Dialog)
        self.brtl_closezb.setGeometry(QtCore.QRect(110, 560, 75, 21))
        self.brtl_closezb.setObjectName(_fromUtf8("brtl_closezb"))
        self.brtl_zbctid = QtGui.QLineEdit(Dialog)
        self.brtl_zbctid.setGeometry(QtCore.QRect(220, 460, 71, 20))
        self.brtl_zbctid.setObjectName(_fromUtf8("brtl_zbctid"))
        self.brtl_info = QtGui.QPushButton(Dialog)
        self.brtl_info.setGeometry(QtCore.QRect(320, 560, 81, 21))
        self.brtl_info.setObjectName(_fromUtf8("brtl_info"))
        self.brtl_zbinfo = QtGui.QPushButton(Dialog)
        self.brtl_zbinfo.setGeometry(QtCore.QRect(220, 550, 75, 21))
        self.brtl_zbinfo.setObjectName(_fromUtf8("brtl_zbinfo"))
        self.brtl_closevhf = QtGui.QPushButton(Dialog)
        self.brtl_closevhf.setGeometry(QtCore.QRect(10, 560, 75, 21))
        self.brtl_closevhf.setObjectName(_fromUtf8("brtl_closevhf"))
        self.brtl_lat = QtGui.QLineEdit(Dialog)
        self.brtl_lat.setGeometry(QtCore.QRect(420, 510, 91, 20))
        self.brtl_lat.setObjectName(_fromUtf8("brtl_lat"))
        self.brtl_close = QtGui.QPushButton(Dialog)
        self.brtl_close.setGeometry(QtCore.QRect(110, 410, 71, 21))
        self.brtl_close.setObjectName(_fromUtf8("brtl_close"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(410, 390, 171, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.brtl_openvhf = QtGui.QPushButton(Dialog)
        self.brtl_openvhf.setGeometry(QtCore.QRect(10, 530, 75, 21))
        self.brtl_openvhf.setObjectName(_fromUtf8("brtl_openvhf"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(220, 320, 71, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.brtl_clean = QtGui.QPushButton(Dialog)
        self.brtl_clean.setGeometry(QtCore.QRect(10, 320, 75, 21))
        self.brtl_clean.setObjectName(_fromUtf8("brtl_clean"))
        self.brtl_lon = QtGui.QLineEdit(Dialog)
        self.brtl_lon.setGeometry(QtCore.QRect(420, 560, 101, 20))
        self.brtl_lon.setObjectName(_fromUtf8("brtl_lon"))
        self.brtl_comboBox = QtGui.QComboBox(Dialog)
        self.brtl_comboBox.setGeometry(QtCore.QRect(110, 370, 69, 22))
        self.brtl_comboBox.setObjectName(_fromUtf8("brtl_comboBox"))
        self.brtl_comboBox.addItem(_fromUtf8(""))
        self.brtl_comboBox.setItemText(0, _fromUtf8(""))
        self.brtl_comboBox.addItem(_fromUtf8(""))
        self.brtl_comboBox.addItem(_fromUtf8(""))
        self.brtl_comboBox.addItem(_fromUtf8(""))
        self.brtl_serial = QtGui.QComboBox(Dialog)
        self.brtl_serial.setGeometry(QtCore.QRect(10, 370, 69, 21))
        self.brtl_serial.setObjectName(_fromUtf8("brtl_serial"))
        self.brtl_openzb = QtGui.QPushButton(Dialog)
        self.brtl_openzb.setGeometry(QtCore.QRect(110, 530, 75, 21))
        self.brtl_openzb.setObjectName(_fromUtf8("brtl_openzb"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(420, 540, 101, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(220, 420, 91, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 480, 181, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(560, 330, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.brtl_leftpierlat = QtGui.QLineEdit(Dialog)
        self.brtl_leftpierlat.setGeometry(QtCore.QRect(570, 350, 81, 20))
        self.brtl_leftpierlat.setObjectName(_fromUtf8("brtl_leftpierlat"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(550, 350, 21, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(550, 380, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.brtl_centerpierlat = QtGui.QLineEdit(Dialog)
        self.brtl_centerpierlat.setGeometry(QtCore.QRect(570, 380, 81, 20))
        self.brtl_centerpierlat.setObjectName(_fromUtf8("brtl_centerpierlat"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(550, 410, 21, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.brtl_rightpierlat = QtGui.QLineEdit(Dialog)
        self.brtl_rightpierlat.setGeometry(QtCore.QRect(570, 410, 81, 20))
        self.brtl_rightpierlat.setObjectName(_fromUtf8("brtl_rightpierlat"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(560, 480, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.brtl_leftpierlon = QtGui.QLineEdit(Dialog)
        self.brtl_leftpierlon.setGeometry(QtCore.QRect(570, 500, 81, 20))
        self.brtl_leftpierlon.setObjectName(_fromUtf8("brtl_leftpierlon"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(550, 500, 21, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(550, 530, 21, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.brtl_centerpierlon = QtGui.QLineEdit(Dialog)
        self.brtl_centerpierlon.setGeometry(QtCore.QRect(570, 530, 81, 20))
        self.brtl_centerpierlon.setObjectName(_fromUtf8("brtl_centerpierlon"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(550, 560, 21, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.brtl_rightpierlon = QtGui.QLineEdit(Dialog)
        self.brtl_rightpierlon.setGeometry(QtCore.QRect(570, 560, 81, 20))
        self.brtl_rightpierlon.setObjectName(_fromUtf8("brtl_rightpierlon"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(680, 370, 151, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.brtl_water = QtGui.QLineEdit(Dialog)
        self.brtl_water.setGeometry(QtCore.QRect(680, 410, 71, 20))
        self.brtl_water.setObjectName(_fromUtf8("brtl_water"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(670, 390, 91, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(220, 370, 91, 20))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(220, 440, 91, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(680, 440, 31, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.brtl_brname = QtGui.QLineEdit(Dialog)
        self.brtl_brname.setGeometry(QtCore.QRect(680, 460, 71, 20))
        self.brtl_brname.setObjectName(_fromUtf8("brtl_brname"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "桥墩主机配置", None))
        self.brtl_dirmax.setText(_translate("Dialog", "0e10", None))
        self.brtl_schipdir.setText(_translate("Dialog", "显示船舶航向", None))
        self.brtl_open.setText(_translate("Dialog", "打开串口", None))
        self.brtl_slinked.setText(_translate("Dialog", "显示发送信息", None))
        self.label_19.setText(_translate("Dialog", "主机ID（Hex,max=ffff）", None))
        self.brtl_zbcmid.setText(_translate("Dialog", "8003", None))
        self.brtl_unstime.setText(_translate("Dialog", "隐藏时间", None))
        self.label_15.setText(_translate("Dialog", "ZigBee本机地址", None))
        self.label.setText(_translate("Dialog", "桥墩主机配置:", None))
        self.brtl_unslinked.setText(_translate("Dialog", "隐藏发送信息", None))
        self.brtl_end.setText(_translate("Dialog", "关闭配置模式", None))
        self.label_17.setText(_translate("Dialog", "主机纬度（Hex）", None))
        self.label_4.setText(_translate("Dialog", "串口", None))
        self.brtl_start.setText(_translate("Dialog", "开启配置模式", None))
        self.brtl_zbconfirm.setText(_translate("Dialog", "确认配置", None))
        self.brtl_id.setText(_translate("Dialog", "0002", None))
        self.brtl_checkvhf.setText(_translate("Dialog", "查询VHF", None))
        self.brtl_stime.setText(_translate("Dialog", "显示时间", None))
        self.brtl_dirmin.setText(_translate("Dialog", "0000", None))
        self.label_5.setText(_translate("Dialog", "波特率", None))
        self.brtl_unschipdir.setText(_translate("Dialog", "隐藏船舶航向", None))
        self.label_21.setText(_translate("Dialog", "船舶航向最大值（Hex,max=ffff）", None))
        self.brtl_chechzb.setText(_translate("Dialog", "查询ZigBee", None))
        self.brtl_confirm.setText(_translate("Dialog", "确认配置", None))
        self.brtl_closezb.setText(_translate("Dialog", "关闭ZigBee", None))
        self.brtl_zbctid.setText(_translate("Dialog", "8004", None))
        self.brtl_info.setText(_translate("Dialog", "主机信息", None))
        self.brtl_zbinfo.setText(_translate("Dialog", "ZigBee信息", None))
        self.brtl_closevhf.setText(_translate("Dialog", "关闭VHF", None))
        self.brtl_lat.setText(_translate("Dialog", "0003887d", None))
        self.brtl_close.setText(_translate("Dialog", "关闭串口", None))
        self.label_20.setText(_translate("Dialog", "船舶航向最小值（Hex）", None))
        self.brtl_openvhf.setText(_translate("Dialog", "开启VHF", None))
        self.label_14.setText(_translate("Dialog", "ZigBee配置:", None))
        self.brtl_clean.setText(_translate("Dialog", "清屏", None))
        self.brtl_lon.setText(_translate("Dialog", "00114f97", None))
        self.brtl_comboBox.setItemText(1, _translate("Dialog", "9600", None))
        self.brtl_comboBox.setItemText(2, _translate("Dialog", "38400", None))
        self.brtl_comboBox.setItemText(3, _translate("Dialog", "115200", None))
        self.brtl_openzb.setText(_translate("Dialog", "开启ZigBee", None))
        self.label_18.setText(_translate("Dialog", "主机经度（Hex）", None))
        self.label_16.setText(_translate("Dialog", "ZigBee对方地址", None))
        self.label_6.setText(_translate("Dialog", "桥墩纬度（Hex）", None))
        self.brtl_leftpierlat.setText(_translate("Dialog", "00037e7b", None))
        self.label_7.setText(_translate("Dialog", "左:", None))
        self.label_8.setText(_translate("Dialog", "中:", None))
        self.brtl_centerpierlat.setText(_translate("Dialog", "00037e71", None))
        self.label_9.setText(_translate("Dialog", "右:", None))
        self.brtl_rightpierlat.setText(_translate("Dialog", "00037e67", None))
        self.label_12.setText(_translate("Dialog", "桥墩经度（Hex）", None))
        self.brtl_leftpierlon.setText(_translate("Dialog", "00114674", None))
        self.label_11.setText(_translate("Dialog", "左:", None))
        self.label_10.setText(_translate("Dialog", "中:", None))
        self.brtl_centerpierlon.setText(_translate("Dialog", "00114671", None))
        self.label_13.setText(_translate("Dialog", "右:", None))
        self.brtl_rightpierlon.setText(_translate("Dialog", "0011466d", None))
        self.label_3.setText(_translate("Dialog", "液位补偿(cm)", None))
        self.brtl_water.setText(_translate("Dialog", "0000", None))
        self.label_2.setText(_translate("Dialog", "（Hex,max=ffff）", None))
        self.label_22.setText(_translate("Dialog", "Hex,max=ffff", None))
        self.label_23.setText(_translate("Dialog", "Hex,max=ffff", None))
        self.label_24.setText(_translate("Dialog", "桥名", None))
        self.brtl_brname.setText(_translate("Dialog", "三洪奇", None))

import winico_rc
